# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform_Init
    displayName: Terraform Init
    jobs:
      - job: Terraform_init
        displayName: Terraform Init
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              backendServiceArm: 'Azure DevOps Pulse (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
              backendAzureRmResourceGroupName: 'terraform-rg10'
              backendAzureRmStorageAccountName: 'terraformbackend0001'
              backendAzureRmContainerName: 'tfcontainer01'
              backendAzureRmKey: 'dev.tfstate'

  - stage: Terraform_Validate
    displayName: Terraform validate
    dependsOn: Terraform_Init
    jobs:
      - job: Terraform_validate
        displayName: Terraform validate
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              backendServiceArm: 'Azure DevOps Pulse (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
              backendAzureRmResourceGroupName: 'terraform-rg10'
              backendAzureRmStorageAccountName: 'terraformbackend0001'
              backendAzureRmContainerName: 'tfcontainer01'
              backendAzureRmKey: 'dev.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'

  - stage: Terraform_Format
    displayName: Terraform Format
    dependsOn: Terraform_Init
    jobs:
      - job: Terraform_Format
        displayName: Terraform Format
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              backendServiceArm: 'Azure DevOps Pulse (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
              backendAzureRmResourceGroupName: 'terraform-rg10'
              backendAzureRmStorageAccountName: 'terraformbackend0001'
              backendAzureRmContainerName: 'tfcontainer01'
              backendAzureRmKey: 'dev.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: 'Azure DevOps Pulse (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
  - stage: Terraform_Plan
    displayName: Terraform Plan
    dependsOn: Terraform_Init
    jobs:
      - job: Terraform_Plan
        displayName: Terraform Plan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              backendServiceArm: 'Azure DevOps Pulse (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
              backendAzureRmResourceGroupName: 'terraform-rg10'
              backendAzureRmStorageAccountName: 'terraformbackend0001'
              backendAzureRmContainerName: 'tfcontainer01'
              backendAzureRmKey: 'dev.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              environmentServiceNameAzureRM: 'Azure DevOps Pulse (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
  - stage: Publish_Artifacts
    displayName: Publish_Artifacts
    dependsOn: Terraform_Init
    jobs:
      - job: Publish_Artifacts
        displayName: Publish_Artifacts
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApp-ASP.Net core/terraform-manifests'
              ArtifactName: 'Terraform-artifact'
              publishLocation: 'Container'